# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 80, 631, 221))
        self.widget.setObjectName("widget")
        self.btn_books = QtWidgets.QPushButton(self.widget)
        self.btn_books.setGeometry(QtCore.QRect(230, 170, 127, 28))
        self.btn_books.setObjectName("btn_books")
        self.btn_laptops = QtWidgets.QPushButton(self.widget)
        self.btn_laptops.setGeometry(QtCore.QRect(230, 65, 127, 28))
        self.btn_laptops.setObjectName("btn_laptops")
        self.btn_users = QtWidgets.QPushButton(self.widget)
        self.btn_users.setGeometry(QtCore.QRect(230, 100, 127, 28))
        self.btn_users.setObjectName("btn_users")
        self.btn_loans = QtWidgets.QPushButton(self.widget)
        self.btn_loans.setGeometry(QtCore.QRect(230, 135, 127, 28))
        self.btn_loans.setObjectName("btn_loans")
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setGeometry(QtCore.QRect(230, 30, 127, 28))
        self.btn_exit.setObjectName("btn_exit")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(230, 30, 129, 170))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_books.setText(_translate("MainWindow", "Gestionar Libros"))
        self.btn_laptops.setText(_translate("MainWindow", "Gestionar Laptops"))
        self.btn_users.setText(_translate("MainWindow", "Gestionar Usuarios"))
        self.btn_loans.setText(_translate("MainWindow", "Gestionar Prestamos"))
        self.btn_exit.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
