# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_books = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_books.setFont(font)
        self.btn_books.setStyleSheet("background-color: #4CAF50; color: white; padding: 10px;")
        self.btn_books.setObjectName("btn_books")
        self.verticalLayout.addWidget(self.btn_books)
        self.btn_users = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_users.setFont(font)
        self.btn_users.setStyleSheet("background-color: #2196F3; color: white; padding: 10px;")
        self.btn_users.setObjectName("btn_users")
        self.verticalLayout.addWidget(self.btn_users)
        self.btn_loans = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_loans.setFont(font)
        self.btn_loans.setStyleSheet("background-color: #FF9800; color: white; padding: 10px;")
        self.btn_loans.setObjectName("btn_loans")
        self.verticalLayout.addWidget(self.btn_loans)
        self.btn_laptops = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_laptops.setFont(font)
        self.btn_laptops.setStyleSheet("background-color: #9C27B0; color: white; padding: 10px;")
        self.btn_laptops.setObjectName("btn_laptops")
        self.verticalLayout.addWidget(self.btn_laptops)
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("background-color: #F44336; color: white; padding: 10px;")
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Gestión de Biblioteca"))
        self.btn_books.setText(_translate("MainWindow", "Gestionar Libros"))
        self.btn_users.setText(_translate("MainWindow", "Gestionar Usuarios"))
        self.btn_loans.setText(_translate("MainWindow", "Gestionar Préstamos"))
        self.btn_laptops.setText(_translate("MainWindow", "Gestionar Laptops"))
        self.btn_exit.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
