# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(320, 110, 129, 170))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_books = QtWidgets.QPushButton(self.widget)
        self.btn_books.setObjectName("btn_books")
        self.verticalLayout.addWidget(self.btn_books)
        self.btn_users = QtWidgets.QPushButton(self.widget)
        self.btn_users.setObjectName("btn_users")
        self.verticalLayout.addWidget(self.btn_users)
        self.btn_loans = QtWidgets.QPushButton(self.widget)
        self.btn_loans.setObjectName("btn_loans")
        self.verticalLayout.addWidget(self.btn_loans)
        self.btn_laptops = QtWidgets.QPushButton(self.widget)
        self.btn_laptops.setObjectName("btn_laptops")
        self.verticalLayout.addWidget(self.btn_laptops)
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_books.setText(_translate("MainWindow", "Gestionar libros"))
        self.btn_users.setText(_translate("MainWindow", "Gestionar usuarios"))
        self.btn_loans.setText(_translate("MainWindow", "Gestionar préstamos"))
        self.btn_laptops.setText(_translate("MainWindow", "Gestionar laptops"))
        self.btn_exit.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
