# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1063, 494)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(210, 20, 841, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 30, 139, 111))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_user_id = QtWidgets.QLineEdit(self.widget)
        self.txt_user_id.setObjectName("txt_user_id")
        self.verticalLayout.addWidget(self.txt_user_id)
        self.txt_name = QtWidgets.QLineEdit(self.widget)
        self.txt_name.setObjectName("txt_name")
        self.verticalLayout.addWidget(self.txt_name)
        self.txt_email = QtWidgets.QLineEdit(self.widget)
        self.txt_email.setObjectName("txt_email")
        self.verticalLayout.addWidget(self.txt_email)
        self.cmb_role = QtWidgets.QComboBox(self.widget)
        self.cmb_role.setObjectName("cmb_role")
        self.cmb_role.addItem("")
        self.cmb_role.addItem("")
        self.verticalLayout.addWidget(self.cmb_role)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(650, 440, 395, 30))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.btn_add_user = QtWidgets.QPushButton(self.widget1)
        self.btn_add_user.setObjectName("btn_add_user")
        self.horizontalLayout.addWidget(self.btn_add_user)
        self.btn_update_user = QtWidgets.QPushButton(self.widget1)
        self.btn_update_user.setObjectName("btn_update_user")
        self.horizontalLayout.addWidget(self.btn_update_user)
        self.btn_delete_user = QtWidgets.QPushButton(self.widget1)
        self.btn_delete_user.setObjectName("btn_delete_user")
        self.horizontalLayout.addWidget(self.btn_delete_user)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.txt_user_id.setPlaceholderText(_translate("Form", "ID del usuario"))
        self.txt_name.setPlaceholderText(_translate("Form", "Nombre"))
        self.txt_email.setPlaceholderText(_translate("Form", "Correo"))
        self.cmb_role.setItemText(0, _translate("Form", "Profesor"))
        self.cmb_role.setItemText(1, _translate("Form", "Estudiante"))
        self.pushButton_4.setText(_translate("Form", "Buscar"))
        self.btn_add_user.setText(_translate("Form", "Agregar"))
        self.btn_update_user.setText(_translate("Form", "Actualizar"))
        self.btn_delete_user.setText(_translate("Form", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
